spring:
  sleuth:
    enabled: true
  profiles:
    active: dev
  application:
    name: provider-demo


server:
  port: 2100


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:8000/eureka'



logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'



