spring:
  profiles:
    active: dev
  application:
    name: zuul-service


server:
  port: 8080


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://localhost:8000/eureka


