spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  profiles:
    active: dev
  application:
    name: caller-demo


server:
  port: 2200



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:8000/eureka'
    registry-fetch-interval-seconds: 4



logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

