spring:
  profiles:
    active: dev
  application:
    name: caller-demo


server:
  port: 2200



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:8000/eureka'
    registry-fetch-interval-seconds: 4



logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
ribbon:
  eureka:
    enabled: true


